version: '3.1'
services:

  rik-db:
    image: postgres:15.3
    container_name: rik-db
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=rik-db-test
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root

  rik-eureka:
    build: rik-eureka
    container_name: rik_eureka
    ports:
      - "8761:8761"
      - "8762:8762"

  rik-gateway:
    build: rik-gateway
    container_name: rik_gateway
    restart: always
    ports:
      - "8080:8080"
      - "8081:8081"
    depends_on:
      - rik-eureka
    environment:
      eureka.client.serviceUrl.defaultZone: http://rik-eureka:8761/eureka/

  rik-service:
    build: rik-service
    container_name: rik_service
    restart: always
    ports:
      - "8090:8090"
      - "8091:8091"
    depends_on:
      - rik-db
      - rik-eureka
      - rik-gateway
    environment:
      eureka.client.serviceUrl.defaultZone: http://rik-eureka:8761/eureka/
      spring.datasource.url: jdbc:postgresql://rik-db:5432/rik-db-test
      spring.datasource.username: root
      spring.datasource.password: root

  rik-auth:
    build: rik-calculation
    container_name: rik_calculation
    restart: always
    ports:
      - "8085:8085"
      - "8086:8086"
    depends_on:
      - rik-db
      - rik-eureka
      - rik-gateway
      - rik-service
    environment:
      eureka.client.serviceUrl.defaultZone: http://rik-eureka:8761/eureka/
      spring.datasource.url: jdbc:postgresql://rik-db:5432/rik-db-test
      spring.datasource.username: root
      spring.datasource.password: root