DROP TABLE IF EXISTS cash_account CASCADE;

CREATE TABLE IF NOT EXISTS cash_account
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    owner        BIGINT                                  NOT NULL,
    red_dollar   NUMERIC                                 NOT NULL,
    green_dollar NUMERIC                                 NOT NULL,
    blue_dollar  NUMERIC                                 NOT NULL,
    CONSTRAINT pk_cash PRIMARY KEY (id),
    CONSTRAINT uq_cash_owner_id FOREIGN KEY (owner) REFERENCES users (id),
    CONSTRAINT uq_cash_owner UNIQUE (owner),
    CONSTRAINT positive_cash_red CHECK ( red_dollar >= 0 ),
    CONSTRAINT positive_cash_green CHECK ( green_dollar >= 0 ),
    CONSTRAINT positive_cash_blue CHECK ( blue_dollar >= 0 )
);